apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "points-devops.fullname" . }}
  labels:
    {{- include "points-devops.labels" . | nindent 4 }}
data:
  blue.html: |
    This is the blue deployment!
  green.html: |
    This is the green deployment!

